DROP TABLE items IF EXISTS;
DROP TABLE inventories IF EXISTS;


CREATE TABLE items (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name      VARCHAR(30),
  category  VARCHAR(30),
  rarity    VARCHAR(30)
);

CREATE TABLE inventories (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_name    VARCHAR(30),
  max_size      VARCHAR(30)
);